### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Xeros08** [Fy-/FyWorld#2]
Hello! Im **Xeros08**, fellow **Rimworld** player and modder.
Worked in officilly translating the before mentioned game to Spanish, and **GameDev** is my hobby and ideal job.

I was, and still am, Interested in (if you did manage to do that) how did you manage to make the power conduit sistem (or even a copy, like water for example) work.

I finally found someone that tried to replicate Rimworld, and that had open sourced the project, but Its been 2 months since you did anything.

To which I ask. Are you tired of the project? or just out of Ideas?
Heck, even things like university or life could be a cause.
I'd love to hear an answer from you, but don't get too personal ;)

**Comment by Fy-** [comment]
Hey, thanks for your interest in FyWorld. The project is not dead per se, I mean I loved to continue but I simply don't have the time right now. I'm working 7 to 10h a day and it will continue like this for at least a few months. I would prefer to work on FyWorld all day long but FyWorld does not pay the bills sadly.
